apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  namespace: data-platform
spec:
  connector:
    hive:
      s3:
        inline:
          host: s3-eu-central-2.ionoscloud.com
          port: 443
          accessStyle: VirtualHosted
          credentials:
            secretClass: ionos-s3-credentials
          tls:
            verification:
              server: {}
