apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces/data-platform.yaml
  - ../../operators/stackable-operators.yaml
  - ../../storage/minio.yaml
  - ../../hive/hive-metastore.yaml
  - ../../trino/trino-catalog-hive.yaml
  - ../../trino/trino-cluster.yaml
patches:
  - path: patches-resources.yaml
