apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: data-platform
spec:
  storageClassName: ionos-enterprise-hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: data-platform
spec:
  storageClassName: ionos-enterprise-hdd
