apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/data-platform.yaml
  - operators/stackable-operators.yaml
  - storage/minio.yaml
  - storage/s3-connection.yaml
  - storage/s3-bucket.yaml
  - postgres/postgres.yaml
  - hive/hive-metastore.yaml
  - trino/trino-catalog-hive.yaml
  - trino/trino-cluster.yaml
