apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  namespace: data-platform
  labels:
    trino: trino
spec:
  connector:
    hive:
      metastore:
        configMap: hive-metastore
      s3:
        endpoint: http://minio.data-platform.svc.cluster.local:9000
        accessKey:
          secret:
            name: minio-credentials
            key: rootUser
        secretKey:
          secret:
            name: minio-credentials
            key: rootPassword
        pathStyleAccess: true
        ssl:
          enabled: false
