apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
  name: hive
  namespace: data-platform
  labels:
    trino: trino
spec:
  connector:
    hive:
      metastore:
        configMap: hive-metastore
      s3:
        inline:
          host: minio.data-platform.svc.cluster.local
          port: 9000
          accessStyle: Path
          credentials:
            secretClass: minio-s3-credentials
